### ISSUE TITLE
unity那个项目运行起来，好多如下报错

### ISSUE THREAD

**Issue by moto2002** [egametang/Egametang#2]
I:\GitHub\Egametang\Unity\Assets\Scripts\Component\Scene\MessageComponent.cs(31,31): Error CS1056: 意外的字符“$” (CS1056) (Assembly-CSharp)

这里的"$"是不是有问题啊

**Comment by egametang** [comment]
这是C#6.0语法,你关了Unity再重新启动Unity应该就行了
